# container base https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
sudo: false
dist: trusty

branches:
  only:
    - master

language: go

go:
  - "1.11"

env:
  global:
    - GOOS=linux
    - GOARCH=amd64

before_install:
  - export PATH=$PATH:$GOPATH/bin

install:
  - make install

script:
  - make test
  - make build

cache:
  directories:
    - vendor
    - $GOPATH/bin

addons:
  artifacts:
    paths:
      - hakaru
      - tools
      - provisioning/instance
    bucket: sunrise2018-hakaru-artifacts
    target_paths: latest:$TRAVIS_COMMIT
    s3_region: ap-northeast-1
